version: '3.8'
services:
  weaviate:
    image: semitechnologies/weaviate:1.21.2
    ports:
      - "8080:8080"
    environment:
      - QUERY_DEFAULTS_LIMIT=20
      - AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED=true
      - PERSISTENCE_DATA_PATH=/var/lib/weaviate
    volumes:
      - ../../volumes/vector-db:/var/lib/weaviate

  mlflow-server:
    image: python:3.10-slim
    ports:
      - "5555:5000"
    volumes:
      - ../../volumes/mlflow:/mlflow
    command: >
      bash -c "pip install mlflow && 
               mlflow server --backend-store-uri file:///mlflow 
                            --default-artifact-root file:///mlflow/artifacts 
                            --host 0.0.0.0 --port 5000"